stages:
    - build
    - test

build:web:
    image: node:10.13.0
    stage: build
    script:
        - "cd SloshyDoshMan.Web"
        - "npm ci"
        - "npm run build"
    
build:client:
    image: microsoft/dotnet/core/sdk:2.2
    stage: build
    script:
        - "dotnet build SloshyDoshMan.Client"

build:service:
    image: microsoft/dotnet/core/sdk:2.2
    stage: build
    script:
        - "dotnet build SloshyDoshMan.Service"

test:
    image: microsoft/dotnet/core/sdk:2.2
    stage: test
    script:
        - "cd SloshyDoshMan.Tests"
        - "dotnet test --collect:\"XPlat Code Coverage\""
        - "less ./TestResults/*/coverage.cobertura.xml"