image: microsoft/dotnet:latest

stages:
    - build
    - test

before_script:
    - "dotnet restore SloshyDoshMan.Client"
    - "dotnet restore SloshyDoshMan.Service"

build:
    stage: build
    script:
        - "dotnet build SloshyDoshMan.Client"
        - "dotnet build SloshyDoshMan.Service"