image: microsoft/dotnet:latest

stages:
    - build
    - test

build:
    stage: build
    script:
        - "dotnet build SloshyDoshMan.Client"
        - "dotnet build SloshyDoshMan.Service"

test:
    stage: test
    script:
        - "dotnet test SloshyDoshMan.Tests"