stages:
    - build
    - test

build:web:
    image: node:10.13.0
    stage: build
    script:
        - "cd SloshyDoshMan.Web"
        - "npm ci"
        - "npm run build"
    artifacts:
        name: "$CI_JOB_NAME"
        paths:
            - SloshyDoshMan.Web/dist

build:client:
    image: mcr.microsoft.com/dotnet/core/sdk:2.2
    stage: build
    script:
        - "dotnet publish SloshyDoshMan.Client -o ../client"
    artifacts:
        name: "$CI_JOB_NAME"
        paths:
            - client

build:service:
    image: mcr.microsoft.com/dotnet/core/sdk:2.2
    stage: build
    script:
        - "dotnet publish SloshyDoshMan.Service -o ../service"
    artifacts:
        name: "$CI_JOB_NAME"
        paths:
            - service

test:
    image: mcr.microsoft.com/dotnet/core/sdk:2.2
    stage: test
    script:
        - "cd SloshyDoshMan.Tests"
        - "dotnet test --collect:\"XPlat Code Coverage\""
        - "head -3 ./TestResults/*/coverage.cobertura.xml"