stages:
    - build
    - test

build:web:
    image: node:10.13.0
    stage: build
    script:
        - "cd SloshyDoshMan.Web"
        - "npm ci"
        - "npm run build"
    
build:client:
    image: microsoft/dotnet:latest
    stage: build
    script:
        - "dotnet build SloshyDoshMan.Client"

build:service:
    image: microsoft/dotnet:latest
    stage: build
    script:
        - "dotnet build SloshyDoshMan.Service"

test:
    image: microsoft/dotnet:latest
    stage: test
    script:
        - "dotnet test SloshyDoshMan.Tests --collect:""XPlat Code Coverage"""