CREATE DATABASE kf2stats
    WITH 
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'English_United States.1252'
    LC_CTYPE = 'English_United States.1252'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;

GRANT TEMPORARY, CONNECT ON DATABASE kf2stats TO PUBLIC;
GRANT ALL ON DATABASE kf2stats TO postgres;
GRANT TEMPORARY, CONNECT ON DATABASE kf2stats TO kf2statsuser;

ALTER DEFAULT PRIVILEGES
GRANT ALL ON TABLES TO postgres;

ALTER DEFAULT PRIVILEGES
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLES TO kf2statsuser;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";